apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-servicemonitor
  labels:
    app: kafka
    kafka_cr: kafka
    release: monitoring
spec:
  selector:
    matchLabels:
      app: kafka
      kafka_cr: kafka
  namespaceSelector:
    matchNames:
    - kafka
  # transfer service labels to metrics
  targetLabels:
  - cluster_name
  # transfer pod labels to metrics
  podTargetLabels:
  - app
  - kafka_cr
  - configGroup
  - brokerId
  endpoints:
  - interval: 10s
    port: metrics
    path: /metrics
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_ip]
      separator: ;
      regex: (.*)
      targetLabel: pod_ip
      replacement: $1
      action: replace
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cruisecontrol-servicemonitor
  labels:
    app: cruisecontrol
    kafka_cr: kafka
    release: monitoring
spec:
  selector:
    matchLabels:
      app: cruisecontrol
  namespaceSelector:
    matchNames:
    - kafka
  # transfer service labels to metrics
  targetLabels:
  - cluster_name
  # transfer pod labels to metrics
  podTargetLabels:
  - app
  - kafka_cr
  endpoints:
  - interval: 10s
    port: metrics
    path: /metrics
    honorLabels: true
