apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zookeeper-servicemonitor
  labels:
    app: zk
    kafka_cr: kafka
    release: monitoring
spec:
  selector:
    matchLabels:
      app: zk
  namespaceSelector:
    matchNames:
    - zookeeper
  endpoints:
  - interval: 10s
    port: metrics
    path: /metrics
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_ip]
      separator: ;
      regex: (.*)
      targetLabel: pod_ip
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_name]
      separator: ;
      regex: (.*)
      targetLabel: pod_name
      replacement: $1
      action: replace
---
